workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master

version: 2
jobs:
  test:
    working_directory: /home/circleci/chablis
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/node:10.15.0-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test -- --runInBand --coverage --bail
      - run: npm publish
